### ISSUE TITLE
Post is tweeted even though checkbox is not enabled

### ISSUE THREAD

**Issue by sumobi** [postpromoterpro/post-promoter-pro#153]
When using EDD and PPP, a download was tweeted even though it was set to not to. I've experienced this on the RCP site and @pippinsplugins has seen it before also.

**Comment by cklosowski** [comment]
Is this the `on publish` shares @sumobi

**Comment by sumobi** [comment]
@cklosowski yep when I published a download for the first time, with that option disabled, it still tweeted the download.

**Comment by pippinsplugins** [comment]
Still happening to me.

**Comment by cklosowski** [comment]
Ok as far as I can tell, this isn't occurring on the `release/2.3` branch. I'm going to wrap it up for beta here shortly, and i'll keep this open to verify if we're still seeing this happen.

**Comment by cklosowski** [comment]
Punting to 2.3.1 to see if it resolves for you guys in 2.3. Some changes were made in the way that the saves happen and data is stored.

**Comment by cklosowski** [comment]
Just saw this happen too. Will dig in this weekend.

**Comment by cklosowski** [comment]
@sumobi Curious, the time I had this happen. I checked the box to tweet at the time of publish, scheduled the post, then decided to publish the post now, and tweet later so I changed the publish time, and unchecked the box...then it tweeted on publish.

Is that something you've done too? Or was it a new post unchecked, and published? I think it's a logic in the way that a post that's already been saved and the order of the actions run with post meta...but I want to be sure.

**Comment by pippinsplugins** [comment]
That is definitely something I've done

**Comment by sumobi** [comment]
@cklosowski I'm not 100% sure but that certainly sounds familiar

**Comment by cklosowski** [comment]
Cool thanks guys I'll investigate, I can't get it to happen on a straight up new post and publish so I'm guessing it's happening in a race condition/odd timing of a `save_post` hook.

**Comment by cklosowski** [comment]
Confirmed, that's the issue. When something is checked to be shared on publish, saved as a draft or future post, then manually updated to uncheck the box and published in the same action as saving the uncheck, it sends it still. This is due to the order of events for the actions of `save_post` and `transition_post_status`. Will fix this up.

**Comment by pippinsplugins** [comment]
:+1:
